version: "3"
services:
  master:
    build: .
    container_name: hadoop-master
    hostname: master
    ports:
      - "9870:9870"  # HDFS Web UI
      - "8088:8088"  # YARN Web UI
      - "9000:9000"  # HDFS
      - "22:22"      # SSH
    volumes:
      - ./master:/opt/hadoop/etc/hadoop
    command: bash -c "/usr/sbin/sshd && tail -f /dev/null"
    privileged: true

  worker1:
    build: .
    container_name: hadoop-worker1
    hostname: worker1
    depends_on: [master]
    ports:
      - "22"  # SSH
    volumes:
      - ./worker1:/opt/hadoop/etc/hadoop
    command: bash -c "/usr/sbin/sshd && tail -f /dev/null"
    privileged: true

  worker2:
    build: .
    container_name: hadoop-worker2
    hostname: worker2
    depends_on: [master]
    ports:
      - "22"  # SSH
    volumes:
      - ./worker2:/opt/hadoop/etc/hadoop
    command: bash -c "/usr/sbin/sshd && tail -f /dev/null"
    privileged: true

networks:
  default:
    name: hadoop-net